try {
	${1:doSomething}
} catch (${2:XxxException} $e) {
	echo 'Caught exception: ',  $e->getMessage(), "\n";
	${3:handleException}
}${4}
